/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SystemStatus {
    bool has_depth;
    float depth;
    bool has_ref_depth;
    float ref_depth;
    bool has_status;
    bool status;
    bool has_piston_pos;
    float piston_pos;
    bool has_control_volume;
    float control_volume;
    bool has_message;
    char message[500];
} SystemStatus;

typedef struct _Command {
    bool has_target_depth;
    float target_depth;
    bool has_enable;
    bool enable;
} Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SystemStatus_init_default                {false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define Command_init_default                     {false, 0, false, 0}
#define SystemStatus_init_zero                   {false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define Command_init_zero                        {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SystemStatus_depth_tag                   1
#define SystemStatus_ref_depth_tag               2
#define SystemStatus_status_tag                  3
#define SystemStatus_piston_pos_tag              4
#define SystemStatus_control_volume_tag          5
#define SystemStatus_message_tag                 6
#define Command_target_depth_tag                 1
#define Command_enable_tag                       2

/* Struct field encoding specification for nanopb */
#define SystemStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    depth,             1) \
X(a, STATIC,   OPTIONAL, FLOAT,    ref_depth,         2) \
X(a, STATIC,   OPTIONAL, BOOL,     status,            3) \
X(a, STATIC,   OPTIONAL, FLOAT,    piston_pos,        4) \
X(a, STATIC,   OPTIONAL, FLOAT,    control_volume,    5) \
X(a, STATIC,   OPTIONAL, STRING,   message,           6)
#define SystemStatus_CALLBACK NULL
#define SystemStatus_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    target_depth,      1) \
X(a, STATIC,   OPTIONAL, BOOL,     enable,            2)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL

extern const pb_msgdesc_t SystemStatus_msg;
extern const pb_msgdesc_t Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SystemStatus_fields &SystemStatus_msg
#define Command_fields &Command_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             7
#define MESSAGES_PB_H_MAX_SIZE                   SystemStatus_size
#define SystemStatus_size                        524

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
