# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"m\n\rsystem_status\x12\r\n\x05\x64\x65pth\x18\x01 \x01(\x02\x12\x11\n\tref_depth\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\x12\n\npiston_pos\x18\x04 \x01(\x02\x12\x16\n\x0e\x63ontrol_volume\x18\x05 \x01(\x02\"/\n\x07\x63ommand\x12\x14\n\x0ctarget_depth\x18\x01 \x01(\x02\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEM_STATUS']._serialized_start=18
  _globals['_SYSTEM_STATUS']._serialized_end=127
  _globals['_COMMAND']._serialized_start=129
  _globals['_COMMAND']._serialized_end=176
# @@protoc_insertion_point(module_scope)
