/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _system_status {
    float dept;
    float ref_depth;
    bool status;
    float piston_pos;
    float control_volume;
} system_status;

typedef struct _command {
    float target_depth;
    bool enable;
} command;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define system_status_init_default               {0, 0, 0, 0, 0}
#define command_init_default                     {0, 0}
#define system_status_init_zero                  {0, 0, 0, 0, 0}
#define command_init_zero                        {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define system_status_dept_tag                   1
#define system_status_ref_depth_tag              2
#define system_status_status_tag                 3
#define system_status_piston_pos_tag             4
#define system_status_control_volume_tag         5
#define command_target_depth_tag                 1
#define command_enable_tag                       2

/* Struct field encoding specification for nanopb */
#define system_status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    dept,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    ref_depth,         2) \
X(a, STATIC,   SINGULAR, BOOL,     status,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    piston_pos,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    control_volume,    5)
#define system_status_CALLBACK NULL
#define system_status_DEFAULT NULL

#define command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    target_depth,      1) \
X(a, STATIC,   SINGULAR, BOOL,     enable,            2)
#define command_CALLBACK NULL
#define command_DEFAULT NULL

extern const pb_msgdesc_t system_status_msg;
extern const pb_msgdesc_t command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define system_status_fields &system_status_msg
#define command_fields &command_msg

/* Maximum encoded size of messages (where known) */
#define MESSAGES_PB_H_MAX_SIZE                   system_status_size
#define command_size                             7
#define system_status_size                       22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
