/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SYSTEM_STATUS_PB_H_INCLUDED
#define PB_SYSTEM_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _system_status {
    float dept;
    float ref_depth;
    bool status;
    float piston_pos;
    float control_volume;
} system_status;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define system_status_init_default               {0, 0, 0, 0, 0}
#define system_status_init_zero                  {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define system_status_dept_tag                   1
#define system_status_ref_depth_tag              2
#define system_status_status_tag                 3
#define system_status_piston_pos_tag             4
#define system_status_control_volume_tag         5

/* Struct field encoding specification for nanopb */
#define system_status_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    dept,              1) \
X(a, STATIC,   REQUIRED, FLOAT,    ref_depth,         2) \
X(a, STATIC,   REQUIRED, BOOL,     status,            3) \
X(a, STATIC,   REQUIRED, FLOAT,    piston_pos,        4) \
X(a, STATIC,   REQUIRED, FLOAT,    control_volume,    5)
#define system_status_CALLBACK NULL
#define system_status_DEFAULT NULL

extern const pb_msgdesc_t system_status_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define system_status_fields &system_status_msg

/* Maximum encoded size of messages (where known) */
#define SYSTEM_STATUS_PB_H_MAX_SIZE              system_status_size
#define system_status_size                       22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
