- ros_topic_name: "piston_volume"
  gz_topic_name: "model/vbs/buoyancy_engine"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  subscriber_queue: 5
  publisher_queue: 6
  lazy: false
  direction: ROS_TO_GZ

- ros_topic_name: "depth"
  gz_topic_name: "model/vbs/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  subscriber_queue: 5
  publisher_queue: 6
  lazy: false
  direction: GZ_TO_ROS

- ros_topic_name: "vbs_imu"
  gz_topic_name: "vbs/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS